import type { Metadata } from "next";
import { Signika, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";

const signika = Signika({
  variable: "--font-signika",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`${signika.variable} ${roboto.variable} antialiased`}
      >
      <Navbar />
        {children}
      </body>
    </html>
  );
}
